name: HRSDesktop
options:
  bundleIdPrefix: com.b4db1r3
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0

targets:
  HRSDesktop:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: HRSDesktop/Sources
    resources:
      - path: HRSDesktop/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.b4db1r3.hrsdesktop.ios
        INFOPLIST_FILE: HRSDesktop/Info.plist
